- contracts/DebtRegistry.sol
- contracts/TermsContract.sol
- contracts/examples/NFTTermsContract.sol
- contracts/examples/SimpleInterestTermsContract.sol
- test/ts/integration/debt_kernel.ts
- test/ts/unit/debt_registry.ts
This change reflects a request from the Zeppelin Solutions team and affects the following aspects of the code base:
1 - The `TermsContract` interface no longer relies on block numbers, but block timestamps
2- Entries in the `DebtRegistry` no longer store block numbers, but block timestamps
They submitted the following in requesting this change:
> Implementors of the TermsContracts interface are expected to define repayment terms as a function of block numbers, as documented and seen in the function signatures of getExpectedRepaymentValue and getValueRepaid. To aid in this, entries in DebtRegistry record the issuance block number.
> Block timestamps have a small risk of miner manipulation within a range of minutes, so it is recommended to use block numbers for certain usecases where this …
> Do not rely on block number; instead use the block's timestamp

- contracts/libraries/PermissionsLib.sol
- test/ts/unit/debt_registry.ts
Revoking permissions previously was O(n). It has now been implemented to be O(1) because we store the index of the agent in a mapping housed in the `Permissions` struct.
This changes reflects the request from the Zeppelin audit. They write:
> The revokeAuthorization function in PermissionsLib performs a linear search over an array of unbounded size. Through subsequent calls to authorize, the array could grow to a size so large that a call to revokeAuthorization would be prohibitively expensive and not fit in a block.
> Consider modifying the Permissions struct to include a mapping to save the index of each authorized address in the authorizedAgents array. In this way it will not be necessary to perform a linear search at all.
> Improve efficiency of revoking permissions

- migrations/2_deploy_dharma_contracts.ts
- migrations/3_deploy_test_contracts.ts
- migrations/4_authorize_contract_interactions.ts
- test/ts/integration/debt_kernel.ts
- test/ts/unit/debt_registry.ts
In debugging a mysterious `revert` error, we discovered that:
1. There are several locations in which we redundantly add authorized agents to certain contracts' permissions.  Easy fix -- we either remove the redundant method calls, or make sure that those tests are working with a freshly deployed contract (as opposed to the contract deployed in the migrations).
2. `truffle test` silently runs a migration in which it saves artifacts to a temporary directory (which is _not_ `build/contracts`).  In contrast, when `truffle migrate` is run, artifacts are stored in `build/contracts`.  This creates idiosyncratic situations in which our generated typings (which pull contract artifacts stored in `build/contracts`) do not have access to the recently stored contract artifacts generated in `truffle …
> Remove redundant agent authorizations + do not leverage generated typings in migrations

- contracts/libraries/PermissionsLib.sol
This is a minor fix but ensures that we clean up our unused memory after removing an agent from our array of authorized agents.
I also added documentation to the revoke permissions method as it does involve a number of steps.
The folks at Zeppelin wrote the following in requesting this change:
> The revokeAuthorization function in PermissionsLib removes the given address from the authorizedAgents array. The algorithm does not correctly consider the edge case when the array is reduced from length 1 to length 0. The new array length is correctly set to 0, but the address previously in the list will remain in storage, out of bounds.
> Although this is unlikely to cause a problem for the semantics of the contracts, consider zeroing out the last slot in the array before decrementing its …
> Clean up memory that's no longer used

- contracts/DebtKernel.sol
- Up the amount to 8000
- Mark both functions as view so they'll eventually compile down to static calls
- Actually enforce the gas limit for `getAllowance`
> Partially address concerns Zeppelin raised concerning the external query gas limit

- contracts/DebtRegistry.sol
- test/ts/unit/debt_registry.ts
There is now a modifier that ensures `insert` and `modifyBeneficiary` do not specify a null beneficiary.
> Add checks in `insert` and in `modifyBeneficiary` to reject null beneficiaries.

- contracts/DebtRegistry.sol
- contracts/DebtToken.sol
In this PR, we 
- Remove the `whenNotPaused` check from the `revokeInsertAgentAuthorization` method, given that none of the other `PermissionsLib` related methods in `DebtRegistry` have pausable operations.  This is secure because the `revokeInsertAgentAuthorization` method can only be activated by the contract's `owner` -- namely, Dharma Labs.
- Override the `_approve()` method of the `DebtToken.sol` such that approvals can be paused at any given point in time.
In the words of our auditors:
> The main functionality of DebtRegistry is correctly guarded with whenNotPaused modifiers to ensure they cannot be used when the contract is in “paused” state. There are other non-constant functions in the contract (those related to permissions) which are inconsistently guarded: …
> Make Pausable operations more consistent in DebtRegistry and DebtToken

- contracts/DebtRegistry.sol
The `Issuance` data structure was unnecessarily duplicated in the `DebtRegistry.sol` file.  We remove for both code cleanliness and avoiding any logic inconsistencies.
For reference, commentary from our auditors:
> There are two Issuance structs, one defined in DebtKernel and another one in DebtRegistry, which are basically the same, except for one member. This duplication could cause problems if the two data structure definitions ever get out of sync during development. Consider having one definition in a central place, together with the relevant operations defined as functions.
> remove unused `Issuance` data structure from `DebtRegistry.sol`

- contracts/DebtToken.sol
- test/ts/unit/debt_token.ts
Logic in the `DebtToken.sol` contract is fairly brittle in that, by overriding certain functions of the class from which it inherits, it tries to shoehorn the DebtRegistry as the primary data layer for the NFT.  Our auditors suggested to instead maintain parallel data stores for the debt tokens generated via Dharma protocol -- one in the actual DebtRegistry, and another in the `DebtToken` file itself.   This fix attempts to do so.
For reference, per the OpenZeppelin audit:
> DebtToken extends NonFungibleToken and redefines the latter’s _setTokenOwner and _ownerOf internal functions, so that they modify the DebtRegistry instead of the NFT’s own tracking of ownership. This seems to result in coherent behavior, but we think it’s an unnecessary meddling with NonFungibleToken’s semantics, and …
> De-duplicate `ownerOf()` logic from `DebtToken.sol`

- contracts/RepaymentRouter.sol
- contracts/TermsContract.sol
- contracts/examples/SimpleInterestTermsContract.sol
- contracts/test/mocks/MockDebtToken.sol
- test/ts/integration/repayment_router.ts
- test/ts/logs/repayment_router.ts
- test/ts/unit/repayment_router.ts
- test/ts/unit/token_transfer_proxy.ts
- Fix tests
- Address compiler warnings
- rename `getValueRepaid` to `getValueRepaidToDate`
- Delete `LogNFTRepayment` event
- `SimpleInterestTermsContract` should explicitly adopt `TermsContract` interface
> Fixes and improvements to remove-nft-terms branch

- contracts/examples/SimpleInterestTermsContract.sol
- test/ts/unit/simple_interest_terms_contract.ts
- Modifier ensures that the contract mapped to the agreement id passed to `getExpectedRepaymentValue` is also the actual contract executing the code.
> Protect `getExpectedRepaymentValue` with modifier

- contracts/DebtKernel.sol
- contracts/TermsContract.sol
- contracts/examples/CompoundInterestTermsContract.sol
- contracts/examples/SimpleInterestTermsContract.sol
- contracts/examples/TermsContractRegistry.sol
- contracts/test/mocks/MockTermsContract.sol
- contracts/test/terms_contracts/DummyCollateralizedContract.sol
- contracts/test/terms_contracts/IncompatibleTermsContract.sol
- migrations/4_deploy_terms_contracts.js
- package.json
- test/ts/integration/debt_kernel.ts
- test/ts/integration/repayment_router.ts
- test/ts/unit/compound_interest_terms_contract.ts
- test/ts/unit/debt_kernel.ts
- test/ts/unit/simple_interest_terms_contract.ts
There are many cases in which terms contracts will want to execute some sort of logic when the debt agreement is filled.  For example, a collateral-holding terms contract could pull collateral from a debtor _only once_ the debt order is filled, meaning debtors will be able to sign and broadcast collateralized debt orders without having to lock up their assets for an arbitrary period beforehand.
As such, this PR introduces the following:
- add a `#registerTermStart` hook to the the TermsContract interface
- update example terms contracts to include this method
- update DebtKernel to automatically call `#registerTermStart` when issuing debt agreement
- update test suite to cover all of the above.
> Add #registerTermStart hook to Terms Contract

- package-lock.json
- package.json
- test/ts/migrations/2_deploy_dharma_contracts_test.ts
- test/ts/migrations/3_deploy_test_contracts_test.ts
- tslint.json
- yarn.lock
`ts-lint` was throwing the below error for our chai expectation calls:
> unused expression, expected an assignment or function call
We now depend on the node package `tslint-no-unused-expression-chai` to allow us to disable  `no-unused-expression` in favor of `no-unused-expression-chai` which allows us to write expectations like `to.be.true` without complaint.
> Suppress ts-lint error: unused expression, expected an assignment or function call

- contracts/TokenRegistry.sol
- migrations/4_deploy_terms_contracts.js
- package.json
- test/ts/integration/debt_kernel.ts
- test/ts/integration/repayment_router.ts
- test/ts/migrations/3_deploy_test_contracts_test.ts
- tsconfig.json
This PR introduces:
- A `getTokenAddressByIndex` method to the token registry, which returns a token's address given its index in the list of tokens tracked by the registry.  This is useful in allowing us to compactly represent a token in a terms contract parameter string using just its index.
- Some more documentation / minor fixes that enable tests to pass.
> TokenRegistry should store list of tokens it tracks

- contracts/DebtKernel.sol
- contracts/TermsContract.sol
- contracts/examples/CompoundInterestTermsContract.sol
- contracts/examples/SimpleInterestTermsContract.sol
- contracts/test/mocks/MockTermsContract.sol
- contracts/test/terms_contracts/DummyCollateralizedContract.sol
- contracts/test/terms_contracts/IncompatibleTermsContract.sol
- test/ts/unit/compound_interest_terms_contract.ts
- test/ts/unit/debt_kernel.ts
- test/ts/unit/simple_interest_terms_contract.ts
- Add a `debtor` argument to the `registerTermStart` call signature in the terms contract interface, given that, without it, the terms contract has no means of determining who the given agreement's associated debtor is.
- Patch tests / mocks which are broken by this change.
> Update registerTermStart signature to include debtor address

- package.json
- test/ts/unit/collateralized/collateralized_contract.ts
- test/ts/unit/collateralized/runners/register_term_start.ts
- test/ts/unit/collateralized/runners/return_collateral.ts
- test/ts/unit/collateralized/runners/seize_collateral.ts
- test/ts/unit/collateralized/scenarios/successful_collateralization.ts
- test/ts/unit/collateralized/scenarios/successful_return.ts
- test/ts/unit/collateralized/scenarios/successful_seizure.ts
- test/ts/unit/collateralized/scenarios/unsuccessful_collateralization.ts
- test/ts/unit/collateralized/scenarios/unsuccessful_return.ts
- test/ts/unit/collateralized/scenarios/unsuccessful_seizure.ts
- yarn.lock
This PR introduces the following fixes:
- clean up test specification in package.json
- bumps truffle version back up to 4.0.4
- tests more explicitly for whether or not scenarios are throwing in scenario runners
- add '_SCENARIOS' suffix to the variables we use to represent our test scenarios.
- cleaned up runner initialization by reducing redundant argument declarations.
> Fixes suggested by saturnial + graeme to PR#45

- contracts/TokenRegistry.sol
- No longer list tokens by their symbols' hashes, but rather by the symbols themselves
- add a `getTokenSymbolByIndex` method to the `TokenRegistry`
> Add `getTokenSymbolByIndex` method

- .circleci/config.yml
Unlike for dharma.js, I don't think that there is a reason to wait between `yarn chain` and `yarn test` here.
> test: remove sleep from circle build

- artifacts/index.ts
- Removes outdated import statements from `artifacts/index.ts`
> fix: artifacts/index.ts imports from nonexistant TermsContractRegistry

- artifacts/index.ts
- contracts/examples/SimpleInterestTermsContract.sol
- test/ts/unit/simple_interest_terms_contract.ts
- Factors in scaling factor for fixed point interest rate when calculating the expected repayment value of a debt agreement.  This is motivated by the fact that Solidity doesn't support floating point numbers -- as such, we have to choose arbitrary scaling factors and represent floating point numbers (such as interest rates) as fixed point values.  In this case, we choose a scaling factor of 10^4.
- Patches test suite associated with the simple interest terms contract.
> Account for interest rate decimals in calculating expected repayment value

- package.json
- test/ts/test_utils/send_transactions.ts
- types/modules.d.ts
Truffle contract instance cannot handle overloaded methods.
This PR adds a test util to send transaction to an overloaded method.
Example:
```javascript
// send tx to
// safeTransferFrom(address _from, address _to, uint256 _tokenId)
await sendTransaction(
debtTokenTruffle, // truffle contract instance
"safeTransferFrom",
"address,address,uint256",
[
TOKEN_OWNER_1,
TOKEN_OWNER_2,
TOKEN_ID_1,
],
{ from: TOKEN_OWNER_1 }
);
// send tx to
// safeTransferFrom(address _from, address _to, uint256 _tokenId, bytes _data)
await sendTransaction(
debtTokenTruffle, // truffle contract instance
"safeTransferFrom",
"address,address,uint256,bytes",
[
TOKEN_OWNER_1,
TOKEN_OWNER_2,
TOKEN_ID_1,
"some data",
],
{ from: TOKEN_OWNER_1 }
);
```
> test: add test util to send transaction

- contracts/examples/SimpleInterestTermsContract.sol
- test/ts/unit/collateralized_simple_interest_terms_contract.ts
- test/ts/unit/simple_interest_terms_contract.ts
- Interest rates in SimpleInterestTermsContract and inheriting contracts accrue on an aggregate term basis, as opposed to once per amortization period.
- patches tests associated with this change.
> fix: interest rate should accrue on aggregate basis as opposed to periodically

- package.json
- Moved the prepublish script under the 'scripts' category (doesn't seem to work otherwise)
> build: move prepublish script to 'scripts'

- contracts/examples/SimpleInterestTermsContract.sol
In order to resolve ambiguity in which format interest rate is stored, we propose to have a convenient way to convert interest rate to both formats: percent and multiplier.
We introduce two different scaling factors:
- INTEREST_RATE_SCALING_FACTOR_PERCENT = 10^4 for conversion of interest rate into percent format
- INTEREST_RATE_SCALING_FACTOR_MULTIPLIER = 10^6 for conversion of interest rate into multiplier format
> separation of interest rate scaling factors for PERCENT and MULTIPLIER format

- contracts/examples/SimpleInterestTermsContract.sol
- test/ts/factories/terms_contract_parameters.ts
- test/ts/integration/debt_kernel.ts
- test/ts/integration/debt_token.ts
- test/ts/integration/examples/collateralized_simple_interest_terms_contract/runners/collateralized_simple_interest_terms_contract.ts
- test/ts/integration/examples/collateralized_simple_interest_terms_contract/runners/register_term_start.ts
- test/ts/integration/examples/collateralized_simple_interest_terms_contract/runners/unpack_parameters_from_bytes.ts
- test/ts/integration/examples/collateralized_simple_interest_terms_contract/scenarios/index.ts
- test/ts/integration/examples/collateralized_simple_interest_terms_contract/scenarios/successful_register_term_start.ts
- test/ts/integration/examples/collateralized_simple_interest_terms_contract/scenarios/unpack_parameters_from_bytes.ts
- test/ts/integration/examples/simple_interest_terms_contract/runners/register_term_start.ts
- test/ts/integration/examples/simple_interest_terms_contract/runners/simple_interest_terms_contract.ts
- test/ts/integration/examples/simple_interest_terms_contract/scenarios/index.ts
- test/ts/integration/examples/simple_interest_terms_contract/scenarios/successful_register_term_start.ts
- test/ts/integration/examples/simple_interest_terms_contract/scenarios/unpack_parameters_from_bytes.ts
- test/ts/integration/repayment_router.ts
- test/ts/test_utils/units.ts
- test/ts/unit/collateralized_simple_interest_terms_contract.ts
- test/ts/unit/debt_kernel.ts
- test/ts/unit/debt_registry.ts
- test/ts/unit/debt_token.ts
- test/ts/unit/simple_interest_terms_contract.ts
*This PR introduces the following changes*:
- scale down interest amount calculation by a `PERCENTAGE_SCALING_FACTOR` of 100
- Fix tests to account for this.
Alex of Confirmation Labs reported a bug in which `getExpectedRepaymentValue` on `SimpleInterestTermsContract` returned a value which did not seem in line with how interest rate calculations ought to occur -- namely, a principal amount of 2 ETH w/ an interest rate of 1% would return a total expected repayment amount of 4 ETH.   It turns out he ran into a *very* important idiosyncrasy -- our interest rate calculations don't account for the fact that interest percentages have an implicit denominator of 100, i.e. `1% = 1/100`.  Our test suite for `charta` didn't catch this because it calculates `TOTAL_INTEREST` using the same math in …
> Interest rate calculations must account for orders of magnitude in percentages

- migrations/migration_constants.js
- there is a duplicate EOS declaration in the list of tokens we save to the token registry
- minor style fixes added by prettier.
> fix: remove duplicate EOS token migration + nit styling

- package.json
- yarn.lock
- Fix OpenZeppelin's version v1.8.0
> build: make zeppelin's verison fixed

- migrations/migration_constants.js
- migrations/utils.js
- Canonical WETH is deployed already on Kovan.  On Kovan, puts the canonical WETH's address in the TokenRegistry instead of deploying a whole new dummy token.
> build: use deployed canonical WETH address on Kovan

- contracts/DebtKernel.sol
- contracts/DebtRegistry.sol
- contracts/RepaymentRouter.sol
- contracts/test/mocks/MockDebtRegistry.sol
- test/ts/logs/debt_kernel.ts
- test/ts/logs/debt_registry.ts
- changes all references of `issuanceHash` to `agreementId` for consistency
> style: issuanceHash should always be referred to as agreementId

- README.md
- package.json
- Bumps the npm version to 0.1.0
- Adds deployed contract addresses to README
> Mainnet NPM bump

- artifacts/index.ts
- package-lock.json
- package.json
For the actual new artifacts (which is not human-readable), see: https://github.com/dharmaprotocol/charta/pull/152
Note on the version seeming to go from 0.1.4 => 0.1.6:
This is just because master is 1 commit behind (see https://github.com/dharmaprotocol/charta/pull/150), so this will bring it up-to-date.
> Export new artifacts

- package.json
Since migrations are working now, we'll want to reset whenever we migrate for tests.
> build: when migrating, use reset

- package.json
- scripts/generate_address_book.js
Adds a script that can upload a JSON file, containing the current Dharma contract address, to s3.
This is useful, for example, in the experimental repo -- where we will need to migrate contracts that reference the charta artifacts.
Example:
https://console.aws.amazon.com/s3/object/dharma-contract-config/charta/address_book/0.1.20.json?region=us-west-2&tab=overview
> build: create script for uploading address book
